### PR TITLE
move build scripts to npm package

### PR DESCRIPTION
**Pull request by butlerx**

### CODE REVIEW

**Comment by VoyTechnology** [comment]
1. What is the rationale behinds moving it to npm package? I can't really see much benefit right now with this change
2. I've noticed the schema is missing. Does that mean we are no longer checking the pages or am I missing something?

I was personally thinking that converting the page to use Polymer would benefit the site more. What do you think?

**Comment by VoyTechnology** [comment]
+CC @benmcmahon100

**Comment by butlerx** [comment]
polymer would be over kill for techweek, 
the idea of separating it it out is so move all the code todo with generating out of this repo so this one is just front end.
the schema is not the default schema in the npm package and can be replaced if specified in a config

**Comment by VoyTechnology** [comment]
I would disagree that its an overkill. If it had a huge boilerplate associated with it, then yes. While I don't have much experience with Polymer, it seems like the benefits of highly modular code outweigh the disadvantages associated with bringing in a whole framework. Let's just leave the decision to the current webmaster because we can "fight" all day :)

**Comment by butlerx** [comment]
techweek doesn't need modules though

**Pull request merged**
